export default class CommonConstants{
  /**
   * Delay time of simulated login
   */
  static readonly LOGIN_DELAY_TIME = 2000;
  /*

   */
  static readonly FULL_PARENT='100%'

  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;
  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 0;

  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';
  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Mine tab index
   */
  static readonly MINE_TAB_INDEX = 1;


  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;


  /**
   * The width of setting list
   */
  static readonly SET_LIST_WIDTH = '42%';


}